### ISSUE TITLE
Riscv tools stale (on rocketchip dependency)

### ISSUE THREAD

**Issue by StellaCassandra** [ucb-bar/midas-top-release#3]
Checking the supplied version of rocketchip leads to the following riscv-tools dependency:
riscv-tools @ cd78e37 bump tools 10 months ago

For building the most recent Riscv Linux with SMP support [sifive/new/linux@c2daa55](https://github.com/sifive/freedom-u-sdk/tree/new), recommended on the [SW-Dev mailing list](https://groups.google.com/a/groups.riscv.org/forum/#!topic/sw-dev/6AXvIILOpDc), this is too outdated.

I'm locked into using Xilinx Zc706. Hence, I cannot use sifive/freedom instead.

Are there prior versions of Linux with SMP support that work for this configuration?
Any suggestions on how to proceed?

**Comment by StellaCassandra** [comment]
Now that I properly check submodule 'rocket-chip/riscv-tools' is actually skipped. So what's the intended riscv-tools version?

**Comment by davidbiancolin** [comment]
Currently, we are using an older priv 1.9 version of the tools because the BOOM priv 1.10 implementation is not yet stable. 

The submodule pointer in rocket-chip is the correct one. We don't initialize it because it's rather large, and often unnecessary if you've already built the toolchain. In the future we'd consider shallow init-ing it.

We have an internal branch that supports priv 1.10 RC but can't release that for another three weeks.
